import type {VenueOptionCard} from '@/lib/venue-options';

export const AMSTERDAM_NEW_OPENING_META = 'New opening · Amsterdam';

/** Recently opened spots — expands fallback catalog search and “show more”. */
export const AMSTERDAM_NEW_OPENINGS_VENUES: VenueOptionCard[] = [
  {
    id: 'cafe-restaurant-de-baanderij',
    title: 'Café Restaurant De Baanderij',
    subtitle: 'NDSM · IJ waterfront',
    meta: AMSTERDAM_NEW_OPENING_META,
    description:
      'A new living room on the IJ at the NDSM shipyard — always buzzing, always a spot, and a menu full of proper dishes.',
    cta_label: 'Book your table',
    google_rating: 4.5,
    review_count: 380,
    dietary_tags: ['vegetarian-friendly'],
  },
  {
    id: 'rotate-leidseplein',
    title: 'Rotate',
    subtitle: 'Leidseplein · modern dining',
    meta: AMSTERDAM_NEW_OPENING_META,
    description:
      'From the team behind Jondani — just as polished as Beethovenstraat, now on Leidseplein.',
    cta_label: 'Book your table',
    google_rating: 4.6,
    review_count: 290,
    dietary_tags: ['vegetarian-friendly'],
  },
  {
    id: 'leauf-centrum',
    title: 'Leauf',
    subtitle: 'Center · bakery & lunch',
    meta: AMSTERDAM_NEW_OPENING_META,
    description:
      'The little sibling — those richly topped bakery favourites from the original, now in the city center.',
    cta_label: 'Book your table',
    google_rating: 4.4,
    review_count: 410,
    dietary_tags: ['vegetarian-friendly'],
  },
  {
    id: 'broth-petit-zuid',
    title: 'Broth Petit',
    subtitle: 'Zuid · compact ramen bar',
    meta: AMSTERDAM_NEW_OPENING_META,
    description:
      'No time to recover from the flying start — petit Broth in Amsterdam-Zuid, in the former BAUT space.',
    cta_label: 'Book your table',
    google_rating: 4.5,
    review_count: 520,
    dietary_tags: ['limited-veg'],
  },
  {
    id: 'layers-centrum',
    title: 'Layers',
    subtitle: 'Center · French bakery & deli',
    meta: AMSTERDAM_NEW_OPENING_META,
    description: 'The French bakery & deli favourite — now in the center as well as the original neighbourhood spot.',
    cta_label: 'Book your table',
    google_rating: 4.6,
    review_count: 340,
    dietary_tags: ['vegetarian-friendly'],
  },
  {
    id: 'duke-of-tokyo-pijp',
    title: 'Duke of Tokyo',
    subtitle: 'De Pijp · karaoke bar',
    meta: AMSTERDAM_NEW_OPENING_META,
    description: 'Second location in De Pijp — warm up your vocal cords over drinks and Japanese bar snacks.',
    cta_label: 'Book your table',
    google_rating: 4.3,
    review_count: 680,
    dietary_tags: ['limited-veg'],
  },
  {
    id: 'bakery-wolf-zuidas',
    title: 'Bakery Wolf Zuidas',
    subtitle: 'Zuidas · bakery & café',
    meta: AMSTERDAM_NEW_OPENING_META,
    description:
      'Location four — the largest Wolf yet, on the Zuidas where the Wild & The Moon site used to be. To-go Rozengracht and Utrechtsestraat, café Wolvenstraat — and now the suits get a proper filled roll too.',
    cta_label: 'Book your table',
    google_rating: 4.5,
    review_count: 440,
    dietary_tags: ['vegetarian-friendly'],
  },
  {
    id: 'vermouth-jp-heijestraat',
    title: 'Vermouth JP Heijestraat',
    subtitle: 'West · JP Heijestraat 110',
    meta: AMSTERDAM_NEW_OPENING_META,
    description: 'Cool drinks-first bar on JP Heijestraat — vermouth and low-key late nights.',
    cta_label: 'Book your table',
    google_rating: 4.5,
    review_count: 220,
    dietary_tags: ['limited-veg'],
  },
  {
    id: 'pure-wines-bar',
    title: 'Pure Wines',
    subtitle: 'Center · Ruyterkade 143',
    meta: AMSTERDAM_NEW_OPENING_META,
    description:
      'Natural-wine supplier to the city’s restaurants — outgrew the Choux corner and opened their own bar a few doors down. Stock up or stay for a lovingly uncorked glass.',
    cta_label: 'Book your table',
    google_rating: 4.7,
    review_count: 310,
    dietary_tags: ['vegetarian-friendly', 'vegan-friendly'],
  },
  {
    id: 'bar-steel',
    title: 'Bar Steel',
    subtitle: 'Schinkelbuurt · all-day terrace',
    meta: AMSTERDAM_NEW_OPENING_META,
    description:
      'From the Vooges team — breakfast through late-night snacks on a sun-drenched terrace by the water. Schinkelbuurt staycation energy.',
    cta_label: 'Book your table',
    google_rating: 4.5,
    review_count: 360,
    dietary_tags: ['vegetarian-friendly'],
  },
  {
    id: 'la-brutal-taqueria',
    title: 'La Brutal Taquería',
    subtitle: 'De Pijp · Albert Cuyp',
    meta: AMSTERDAM_NEW_OPENING_META,
    description:
      'Mexico City street tacos on the Albert Cuyp — fresh off the press daily, almost forget you’re in Amsterdam.',
    cta_label: 'Book your table',
    google_rating: 4.4,
    review_count: 590,
    dietary_tags: ['limited-veg'],
  },
  {
    id: 'how-is-your',
    title: 'How Is Your',
    subtitle: 'Noord · Papaverhoek',
    meta: AMSTERDAM_NEW_OPENING_META,
    description: 'Natural wine bar on Papaverhoek — easy new weekend date spot.',
    cta_label: 'Book your table',
    google_rating: 4.5,
    review_count: 180,
    dietary_tags: ['vegetarian-friendly', 'vegan-friendly'],
  },
  {
    id: 'chun-bijenkorf',
    title: 'Chun',
    subtitle: 'Center · Japanese buns',
    meta: AMSTERDAM_NEW_OPENING_META,
    description:
      'Third café — queues by the Bijenkorf are for Japanese buns now, in the former pastry shop.',
    cta_label: 'Book your table',
    google_rating: 4.6,
    review_count: 820,
    dietary_tags: ['limited-veg'],
  },
  {
    id: 'omoka-nsdm',
    title: 'Omoka',
    subtitle: 'NDSM · opposite Botel',
    meta: AMSTERDAM_NEW_OPENING_META,
    description: 'Fridays and Saturdays — head to NDSM for the tastiest African dishes (opposite Botel).',
    cta_label: 'Book your table',
    google_rating: 4.7,
    review_count: 240,
    dietary_tags: ['vegetarian-friendly'],
  },
  {
    id: 'arte-vanilla',
    title: 'Arte Vanilla',
    subtitle: 'Center · gelato',
    meta: AMSTERDAM_NEW_OPENING_META,
    description: 'Homemade gelato to nonna’s recipe — the hot-summer essential.',
    cta_label: 'Book your table',
    google_rating: 4.5,
    review_count: 410,
    dietary_tags: ['vegetarian-friendly'],
  },
];
